name: angora

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      rabbit:
        image: rabbitmq:3.8.11-alpine
        ports:
          - "5672:5672"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v -race ./...
        env:
          AMQP_URL: amqp://guest:guest@localhost:5672
